CrearCuentos/Controllers/InicioController.cs
using Microsoft.AspNetCore.Mvc;

namespace CrearCuentos.Controllers
{
    public class InicioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CrearCuentos/Controllers/SesionController.cs
using CrearCuentos.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
//1.- REFERENCES AUTHENTICATION COOKIE
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;

namespace CrearCuentos.Controllers
{
    public class SesionController : Controller
    {
        private readonly CrearCuentosContext _context;

        public SesionController(CrearCuentosContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(Usuario usuario)
        {
            var user = _context.Usuarios
                    .SingleOrDefault(u => u.NombreDeUsuario == usuario.NombreDeUsuario && u.Contraseña == usuario.Contraseña);

            if (user != null)
            {
                //2.- CONFIGURACION DE LA AUTENTICACION
                #region AUTENTICACTION
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.NombreCompletos),
                    new Claim("Correo", user.Correo),
                    new Claim("PermisoInicial", user.PermisoInicial.ToString()), // Agregar PermisoInicial
                    new Claim("PermisoPrimaria", user.PermisoPrimaria.ToString()), // Agregar PermisoPrimaria
                    new Claim("PermisoSecundaria", user.PermisoSecundaria.ToString()) // Agregar PermisoSecundaria
            };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                #endregion
                if(user.Id == 9)
                {
                    return RedirectToAction("Index", "Usuarios");
                }

                return RedirectToAction("Cuento", "Generar");
                
            }
            else
            {
                ModelState.AddModelError("", "Credenciales incorrectas.");
            }

            return View(usuario);
        }

        public async Task<IActionResult> Salir()
        {
            //3.- CONFIGURACION DE LA AUTENTICACION
            #region AUTENTICACTION
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            #endregion

            return RedirectToAction("Login");

        }

    }
}

CrearCuentos/Views/Sesion/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- STYLESHEET CSS FILES -->
    <link rel="stylesheet" href="~/IndexAssets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/IndexAssets/css/animate.min.css">
    <link rel="stylesheet" href="~/IndexAssets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/IndexAssets/css/nivo-lightbox.css">
    <link rel="stylesheet" href="~/IndexAssets/css/nivo_themes/default/default.css">
    <link rel="stylesheet" href="~/IndexAssets/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <style>
        body {
            margin: 0;
            padding: 0;
            background-image: url('../IndexAssets/images/login.png');
            background-size: cover;
            background-position: center;
            font-family: 'Proxima', sans-serif;
            font-size: 16px;
        }

        .login-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .login-box {
            background: rgba(255, 255, 255, 0.8);
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            padding: 20px;
            width: 400px;
        }

            .login-box img {
                max-width: 80px; /* Tamaño de la imagen del logo reducido */
                display: block;
                margin: 0 auto;
                margin-bottom: 25px;
            }

            .login-box h2 {
                text-align: center;
            }

        .form-group {
            margin-bottom: 20px;
        }

        /* Estilo para las cajas de texto */
        .form-control {
            
            border: 1px solid #ccc; /* Borde de la caja de texto */
            border-radius: 5px; /* Borde redondeado */
            padding: 10px; /* Espacio interno */
            box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1); /* Sombra */
        }


        .btn {
            background: #373435;
            border-radius: 4px;
            border: none;
            color: #ffffff;
            font-size: 18px;
            margin-top: 20px;
            width: 120px;
            box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.3); /* Agrega sombra */
            font-family: 'Playfair Display', serif;
        }

            .btn:hover {
                background: #fff;
                color: #373435;
                transition: all 0.4s ease-in-out;
            }

    </style>
</head>
<body>
    <div class="preloader">
        <div class="sk-spinner-rotating-plane sk-spinner"></div>
    </div>
    <div class="container login-container">
        <div class="login-box">
            <img src="~/IndexAssets/images/team3.png" alt="Logo de la empresa">
            <form asp-controller="Sesion" asp-action="Login" method="post" style="margin-bottom:20px;">
                <div class="form-group" style="font-size:18px;">
                    <label for="NombreDeUsuario"><strong>Correo o Nombre de usuario</strong></label>
                    <input type="text" class="form-control" id="NombreDeUsuario" name="NombreDeUsuario" placeholder="ejemplo@gmail.com"/>
                </div>
                <div class="form-group" style="font-size:18px;">
                    <label for="Contraseña"><strong>Contraseña</strong></label>
                    <input type="password" class="form-control" id="Contraseña" name="Contraseña" placeholder="Contraseña"/>
                </div>
                <button type="submit" class="btn">Entrar</button>
                <div class="form-group" style="text-align: center; font-size: 16px; margin-top: 20px;">
                    <a asp-controller="Inicio" asp-action="Index" style="text-decoration: underline; color: #808080;">Regresar</a>
                </div>
            </form>
        </div>
    </div>

    <script src="~/IndexAssets/js/jquery.js"></script>
    <script src="~/IndexAssets/js/bootstrap.min.js"></script>
    <script src="~/IndexAssets/js/nivo-lightbox.min.js"></script>
    <script src="~/IndexAssets/js/smoothscroll.js"></script>
    <script src="~/IndexAssets/js/jquery.sticky.js"></script>
    <script src="~/IndexAssets/js/jquery.parallax.js"></script>
    <script src="~/IndexAssets/js/wow.min.js"></script>
    <script src="~/IndexAssets/js/custom.js"></script>
</body>
</html>